name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Event and branch
      run: |
        echo "Triggering event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref }}"
    - name: Checkout files
      uses: actions/checkout@v3.3.0
    - name: List files
      run: |
        echo "${{ github.repository }} contents:"
        tree
